# @see https://docs.docker.com/compose/#compose-documentation

# Web container
web: &web
    build: ./docker/web
    ports:
        - 10080:80 # Apache
    volumes:
        # Our app folder
        - .:/var/www
        # Shared apache logs
        - ./docker/web/shared/logs/apache2:/var/log/apache2
        # Site enabled
        - ./docker/web/shared/sites-enabled:/etc/apache2/sites-enabled
        # Composer cache
        - ./docker/web/shared/composer-home:/composer-home
        # Shared var
        - ./var:/var/www/var
    working_dir: /var/www
    env_file: ./docker/web/web.env
    environment:
        # Env variables shared with host machines:
        - SYMFONY__FIXTURES__FRONT__FAT__DISABLED
        # Composer shared home:
        - COMPOSER_HOME=/composer-home
    links:
        - mysql

# MySQL container
mysql:
    image: mysql:latest
    ports:
        - 13306:3306
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
        - ./docker/mysql/shared/mysql-data:/var/lib/mysql

# Adminer container
adminer:
    build: ./docker/adminer
    ports:
        - 10081:80 # Apache
    volumes:
        # Let's give our own "sites-enabled" config files to Apache:
        - ./docker/adminer/shared/sites-enabled:/etc/apache2/sites-enabled
    links:
        - mysql
